### ISSUE TITLE
FinestWebViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by sandeeprana011** [TheFinestArtist/FinestWebView-Android#114]
Force Closes on 7.0 device

`AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.takesport, PID: 6255
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.takesport/com.thefinestartist.finestwebview.FinestWebViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                 at com.thefinestartist.finestwebview.helpers.BitmapHelper.getColoredBitmap(BitmapHelper.java:22)
                                                                 at com.thefinestartist.finestwebview.helpers.BitmapHelper.getColoredBitmap(BitmapHelper.java:38)
                                                                 at com.thefinestartist.finestwebview.FinestWebViewActivity.updateIcon(FinestWebViewActivity.java:840)
                                                                 at com.thefinestartist.finestwebview.FinestWebViewActivity.layoutViews(FinestWebViewActivity.java:474)
                                                                 at com.thefinestartist.finestwebview.FinestWebViewActivity.onCreate(FinestWebViewActivity.java:889)
                                                                 at android.app.Activity.performCreate(Activity.java:6672)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
`

**Comment by HaneetGH** [comment]
any solution for this?

**Comment by azizur-rehman** [comment]
Having the same issue unexpectedly, it was working before though. Any update on this?

**Comment by ihssenedr** [comment]
any solution ?
