### ISSUE TITLE
Appcrash when Click on "Open With"

### ISSUE THREAD

**Issue by Nibot1** [TheFinestArtist/FinestWebView-Android#133]
# Crashlytics Stacktrace:

Fatal Exception: java.lang.IllegalStateException: Could not execute method for android:onClick
       at android.view.View$DeclaredOnClickListener.onClick(View.java:5052)
       at android.view.View.performClick(View.java:6213)
       at android.view.View$PerformClick.run(View.java:23645)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at android.view.View$DeclaredOnClickListener.onClick(View.java:5047)
       at android.view.View.performClick(View.java:6213)
       at android.view.View$PerformClick.run(View.java:23645)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by android.os.FileUriExposedException: file:///storage/emulated/0/Anlagenstammblatt/jjfhjn.html exposed beyond app through Intent.getData()
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
       at android.net.Uri.checkFileUriExposed(Uri.java:2346)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9510)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9468)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
       at android.app.Activity.startActivityForResult(Activity.java:4389)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
       at android.app.Activity.startActivityForResult(Activity.java:4348)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
       at android.app.Activity.startActivity(Activity.java:4672)
       at android.app.Activity.startActivity(Activity.java:4640)
       at com.thefinestartist.finestwebview.FinestWebViewActivity.onClick(FinestWebViewActivity.java:949)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.view.View$DeclaredOnClickListener.onClick(View.java:5047)
       at android.view.View.performClick(View.java:6213)
       at android.view.View$PerformClick.run(View.java:23645)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by Nibot1** [comment]
???
