### ISSUE TITLE
Protocol not found

### ISSUE THREAD

**Issue by serkanucar** [TheFinestArtist/FinestWebView-Android#169]
new FinestWebView.Builder(getActivity()).showUrl(true).show("www.google.com");

java.net.MalformedURLException: Protocol not found: www.google.com
at java.net.URL.<init>(URL.java:176)
at java.net.URL.<init>(URL.java:125)
at com.thefinestartist.finestwebview.helpers.UrlParser.getHost(UrlParser.java:12)
com.thefinestartist.finestwebview.FinestWebViewActivity.initializeViews(FinestWebViewActivity.java:554)

**Comment by Cililing** [comment]
It's not valid URI. You have to specifiy protocol, for example - `https://www.google.com`
