### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by jhwsx** [TheFinestArtist/FinestWebView-Android#173]
## Log：
```text
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.leapsi.sudoku.puzzle/com.thefinestartist.finestwebview.FinestWebViewActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x3040005
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2428)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
	at android.app.ActivityThread.access$1200(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5569)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x3040005
	at android.content.res.HwResources.getText(HwResources.java:1299)
	at android.content.res.Resources.getString(Resources.java:398)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:733)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:657)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:798)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:634)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:571)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:332)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:102)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:284)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:129)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:116)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:113)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:281)
	at android.webkit.WebView.<init>(WebView.java:577)
	at android.webkit.WebView.<init>(WebView.java:512)
	at android.webkit.WebView.<init>(WebView.java:495)
	at android.webkit.WebView.<init>(WebView.java:482)
	at android.webkit.WebView.<init>(WebView.java:472)
	at com.thefinestartist.finestwebview.FinestWebViewActivity.bindViews(FinestWebViewActivity.java)
	at com.thefinestartist.finestwebview.FinestWebViewActivity.onCreate(FinestWebViewActivity.java)
	at android.app.Activity.performCreate(Activity.java:6078)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2381)
	... 10 more
android.content.res.Resources$NotFoundException: String resource ID #0x3040005
	at android.content.res.HwResources.getText(HwResources.java:1299)
	at android.content.res.Resources.getString(Resources.java:398)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:733)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:657)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:798)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:634)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:571)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:332)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:102)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:284)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:129)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:116)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:113)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:281)
	at android.webkit.WebView.<init>(WebView.java:577)
	at android.webkit.WebView.<init>(WebView.java:512)
	at android.webkit.WebView.<init>(WebView.java:495)
	at android.webkit.WebView.<init>(WebView.java:482)
	at android.webkit.WebView.<init>(WebView.java:472)
	at com.thefinestartist.finestwebview.FinestWebViewActivity.bindViews(FinestWebViewActivity.java)
	at com.thefinestartist.finestwebview.FinestWebViewActivity.onCreate(FinestWebViewActivity.java)
	at android.app.Activity.performCreate(Activity.java:6078)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2381)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
	at android.app.ActivityThread.access$1200(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5569)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
```

**Comment by jhwsx** [comment]
The reason is that I use `MaterialComponents `theme, which use this dependency:
```gradle
implementation 'com.google.android.material:material:1.1.0-alpha06'
```
After I changed to stable version:
```gradle
implementation 'com.google.android.material:material:1.0.0'
```
The above error is gone, so this issue is not related to this great repository, it's my own fault.
