### ISSUE TITLE
Crash When close and open the FinestWebView

### ISSUE THREAD

**Issue by chihung93** [TheFinestArtist/FinestWebView-Android#35]
``` java
03-09 17:00:23.638 18986-18986/com.muabannhanh E/ActivityThread: Activity com.thefinestartist.finestwebview.FinestWebViewActivity has leaked IntentReceiver android.widget.ZoomButtonsController$1@38d0c09f that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                 android.app.IntentReceiverLeaked: Activity com.thefinestartist.finestwebview.FinestWebViewActivity has leaked IntentReceiver android.widget.ZoomButtonsController$1@38d0c09f that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                     at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:901)
                                                                     at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:702)
                                                                     at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1701)
                                                                     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1681)
                                                                     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1675)
                                                                     at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:495)
                                                                     at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:387)
                                                                     at org.chromium.android_webview.AwZoomControls.invokeZoomPicker(AwZoomControls.java:30)
                                                                     at org.chromium.content.browser.ContentViewCore.onScrollBeginEventAck(ContentViewCore.java:1235)
                                                                     at org.chromium.content.browser.ContentViewCore.nativeOnTouchEvent(Native Method)
                                                                     at org.chromium.content.browser.ContentViewCore.onTouchEventImpl(ContentViewCore.java:1156)
                                                                     at org.chromium.content.browser.ContentViewCore.onTouchEvent(ContentViewCore.java:1120)
                                                                     at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onTouchEvent(AwContents.java:2984)
                                                                     at org.chromium.android_webview.AwContents.onTouchEvent(AwContents.java:2269)
                                                                     at com.android.webview.chromium.WebViewChromium.onTouchEvent(WebViewChromium.java:1983)
                                                                     at android.webkit.WebView.onTouchEvent(WebView.java:2299)
                                                                     at android.view.View.dispatchTouchEvent(View.java:8388)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
                                                                     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
                                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:2781)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
                                                                     at android.view.View.dispatchPointerEvent(View.java:8578)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
                                                                    at android.view.ViewRootImpl$AsyncI
03-09 17:00:25.108 18986-18986/com.muabannhanh D/AndroidRuntime: Shutting down VM
03-09 17:00:25.108 18986-18986/com.muabannhanh E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.muabannhanh, PID: 18986
                                                                 java.lang.IllegalArgumentException: Receiver not registered: android.widget.ZoomButtonsController$1@38d0c09f
                                                                     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:763)
                                                                     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1724)
                                                                     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:517)
                                                                     at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:404)
                                                                     at android.widget.ZoomButtonsController$2.handleMessage(ZoomButtonsController.java:178)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:921)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:716)
```

**Comment by TheFinestArtist** [comment]
Will solve this crash ASAP

**Comment by TheFinestArtist** [comment]
Seems like its a bug of `WebView` which is not fixed for long. https://code.google.com/p/android/issues/detail?id=15694

**Comment by TheFinestArtist** [comment]
I followed this solution. http://stackoverflow.com/a/5966151/1797648
Let me know if there is any same issue occurs!
