### ISSUE TITLE
crash when os's verison > 23

### ISSUE THREAD

**Issue by marvinlix** [TheFinestArtist/FinestWebView-Android#37]
crash log.

``` java
03-14 23:53:36.931 18043 18043 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.support.graphics.drawable.VectorDrawableCompat
03-14 23:53:36.931 18043 18043 E AndroidRuntime:    at com.thefinestartist.finestwebview.FinestWebViewActivity.updateIcon(FinestWebViewActivity.java:833)
03-14 23:53:36.931 18043 18043 E AndroidRuntime:    at com.thefinestartist.finestwebview.FinestWebViewActivity.layoutViews(FinestWebViewActivity.java:469)
03-14 23:53:36.931 18043 18043 E AndroidRuntime:    at com.thefinestartist.finestwebview.FinestWebViewActivity.onCreate(FinestWebViewActivity.java:859)
03-14 23:53:36.931 18043 18043 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:6251)
03-14 23:53:36.931 18043 18043 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
03-14 23:53:36.931 18043 18043 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
```

**Comment by marvinlix** [comment]
`VectorDrawableCompat drawable = (VectorDrawableCompat) ContextCompat.getDrawable(this, drawableRes);`

drawable have to be Drawable

**Comment by TheFinestArtist** [comment]
Oh my god.. Got  you!

**Comment by TheFinestArtist** [comment]
Fixed and released! @marvinlix Thanks for reporting issue!

**Comment by Heri14** [comment]
This problem still persists.

**Comment by cyqluowang** [comment]
This problem still persists.

**Comment by mopsalarm** [comment]
A 'fixed' version is available as jitpack dependency from my repo:
`compile 'com.github.mopsalarm:FinestWebView-Android:2cf36fd5298052490c5bc4535ba6a666c4208202'`
