### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by cyqluowang** [TheFinestArtist/FinestWebView-Android#42]
``` java
org.xmlpull.v1.XmlPullParserException: Binary XML file line #1<vector> tag requires viewportWidth > 0
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:851)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:320)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:49)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:65)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:53)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at java.lang.reflect.Constructor.constructNative(Native Method)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.createView(LayoutInflater.java:597)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:842)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at com.thefinestartist.finestwebview.FinestWebViewActivity.onCreate(FinestWebViewActivity.java:863)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.app.Activity.performCreate(Activity.java:5249)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.app.ActivityThread.access$900(ActivityThread.java:141)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.os.Looper.loop(Looper.java:136)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at android.app.ActivityThread.main(ActivityThread.java:5072)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at java.lang.reflect.Method.invokeNative(Native Method)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at java.lang.reflect.Method.invoke(Method.java:515)
04-06 23:23:26.076 16159-16159/com..aphone.zfjr E/VdcInflateDelegate:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
04-06 23:23:26.076 16159-16159/com."".aphone.zfjr E/VdcInflateDelegate:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by TheFinestArtist** [comment]
Does this solve your issue?
http://stackoverflow.com/a/35624744/1797648

**Comment by TheFinestArtist** [comment]
@cyqluowang Please user android support version 23.2.1 or 23.2.0 I think there is bug with 23.3.0
