### ISSUE TITLE
error with android support library : 23.3.0

### ISSUE THREAD

**Issue by asamaru7** [TheFinestArtist/FinestWebView-Android#46]
x(close) button touch -> error

android support library : 23.2.1 -> ok
android support library : 23.3.0 -> error

```
java.lang.IllegalStateException: Could not find a method onClick(View) in the activity class android.support.v7.widget.TintContextWrapper for onClick handler on view class android.support.v7.widget.AppCompatImageButton with id 'close'
    at android.view.View$1.onClick(View.java:4237)
    at android.view.View.performClick(View.java:5194)
    at android.view.View$PerformClick.run(View.java:20903)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5942)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
 Caused by: java.lang.NoSuchMethodException: onClick [class android.view.View]
    at java.lang.Class.getMethod(Class.java:665)
    at android.view.View$1.onClick(View.java:4230)
    at android.view.View.performClick(View.java:5194) 
    at android.view.View$PerformClick.run(View.java:20903) 
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:145) 
    at android.app.ActivityThread.main(ActivityThread.java:5942) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
```

**Comment by TheFinestArtist** [comment]
Fixed!
