### ISSUE TITLE
com.thefinestartist.finestwebview.FinestWebViewActivity.onClick crash

### ISSUE THREAD

**Issue by PiotrWpl** [TheFinestArtist/FinestWebView-Android#60]
Hello,

Stacktrace from crashlytics.com:

Fatal Exception: java.lang.IllegalStateException: Could not execute method of the activity
       at android.view.View$1.onClick(View.java:3660)
       at android.view.View.performClick(View.java:4162)
       at android.view.View$PerformClick.run(View.java:17082)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4856)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at android.view.View$1.onClick(View.java:3655)
       at android.view.View.performClick(View.java:4162)
       at android.view.View$PerformClick.run(View.java:17082)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4856)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.(Uri.java)
       at android.net.Uri$StringUri.(Uri.java)
       at android.net.Uri.parse(Uri.java:426)
       at com.thefinestartist.finestwebview.FinestWebViewActivity.onClick(FinestWebViewActivity.java:948)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at android.view.View$1.onClick(View.java:3655)
       at android.view.View.performClick(View.java:4162)
       at android.view.View$PerformClick.run(View.java:17082)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4856)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)

Device:
Samsung S Advance
Android 4.1.2

P.s: Thx for this amazing library!

**Comment by MyoZawOoPD** [comment]
I had the same error too.
