### ISSUE TITLE
NullpointerException from Activity oncreate()

### ISSUE THREAD

**Issue by subbuboyapati** [TheFinestArtist/FinestWebView-Android#91]
```
Caused by java.lang.NullPointerException: Call Base.initialize(context) within your Application onCreate() method.
       at com.thefinestartist.Base.getContext(Base.java:30)
       at com.thefinestartist.utils.service.ServiceUtil.getSystemService(ServiceUtil.java:76)
       at com.thefinestartist.utils.service.ServiceUtil.getWindowManager(ServiceUtil.java:251)
       at com.thefinestartist.utils.service.WindowManagerUtil.getDefaultDisplay(WindowManagerUtil.java:19)
       at com.thefinestartist.utils.ui.DisplayUtil.getWidth(DisplayUtil.java:26)
       at com.thefinestartist.finestwebview.FinestWebViewActivity.getMaxWidth(FinestWebViewActivity.java:833)
       at com.thefinestartist.finestwebview.FinestWebViewActivity.layoutViews(FinestWebViewActivity.java:467)
       at com.thefinestartist.finestwebview.FinestWebViewActivity.onCreate(FinestWebViewActivity.java:889)
       at android.app.Activity.performCreate(Activity.java:5133)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by spidfire** [comment]
I got it also. The error came from a OnePlus 2 (ONE A2003)

**Comment by spidfire** [comment]
And also from a Sony and a Samsung
